      REAL FUNCTION PREDUC(T,TD,P,ZSTN,ZREF)

C  Thomas Matejka NOAA/NSSL 8 March 1993

      IMPLICIT NONE
      INCLUDE 'include_constants.inc'
      REAL SPGASC,DTDPDA
      REAL T,TD,P,ZSTN,ZREF,R,DTDPD,DTDPP,DQSDTP,DQSDPP,GAMMA

      R=SPGASC(TD,P)
      DTDPD=DTDPDA(T,TD,P)
      CALL PSEUDO(T,P,DTDPP,DQSDTP,DQSDPP)
      GAMMA=-(DTDPD+DTDPP)*E_GRAV*P/2./R/T
      PREDUC=P*((T-GAMMA*(ZREF-ZSTN))/T)**(E_GRAV/R/GAMMA)
      RETURN
      END
