      SUBROUTINE STATE2(TV,P,DEN)

C  Thomas Matejka NOAA/NSSL 5 May 1993

      IMPLICIT NONE
      INCLUDE 'include_constants.inc'
      INCLUDE 'tmtlib.inc'
      REAL TV,P,DEN

      IF(TV.EQ.TMTLIB_BADFLAG.AND.
     $P.NE.TMTLIB_BADFLAG.AND.
     $DEN.NE.TMTLIB_BADFLAG)THEN
         TV=P*MW_DRY/(DEN*UNIV_GAS)
      ELSEIF(P.EQ.TMTLIB_BADFLAG.AND.
     $TV.NE.TMTLIB_BADFLAG.AND.
     $DEN.NE.TMTLIB_BADFLAG)THEN
         P=DEN*UNIV_GAS*TV/MW_DRY
      ELSEIF(DEN.EQ.TMTLIB_BADFLAG.AND.
     $TV.NE.TMTLIB_BADFLAG.AND.
     $P.NE.TMTLIB_BADFLAG)THEN
         DEN=P*MW_DRY/(UNIV_GAS*TV)
      ENDIF
      RETURN
      END
