      SUBROUTINE STATE1(T,TD,P,DEN)

C  Thomas Matejka NOAA/NSSL 9 March 1993

      IMPLICIT NONE
      INCLUDE 'include_constants.inc'
      INCLUDE 'tmtlib.inc'
      REAL DPSHUM,VAPPS,SPGASC
      REAL T,TD,P,DEN,R,Q

      IF(T.EQ.TMTLIB_BADFLAG.AND.
     $TD.NE.TMTLIB_BADFLAG.AND.
     $P.NE.TMTLIB_BADFLAG.AND.
     $DEN.NE.TMTLIB_BADFLAG)THEN
         R=SPGASC(TD,P)
         T=P/(DEN*R)
      ELSEIF(TD.EQ.TMTLIB_BADFLAG.AND.
     $T.NE.TMTLIB_BADFLAG.AND.
     $P.NE.TMTLIB_BADFLAG.AND.
     $DEN.NE.TMTLIB_BADFLAG)THEN
         Q=(P*MW_DRY/(DEN*UNIV_GAS*T)-1.)*MW_H2O/(MW_DRY-MW_H2O)
         TD=DPSHUM(P,Q)
      ELSEIF(P.EQ.TMTLIB_BADFLAG.AND.
     $T.NE.TMTLIB_BADFLAG.AND.
     $TD.NE.TMTLIB_BADFLAG.AND.
     $DEN.NE.TMTLIB_BADFLAG)THEN
         P=(DEN*UNIV_GAS*T-VAPPS(TD)*(MW_DRY-MW_H2O))/MW_DRY
      ELSEIF(DEN.EQ.TMTLIB_BADFLAG.AND.
     $T.NE.TMTLIB_BADFLAG.AND.
     $TD.NE.TMTLIB_BADFLAG.AND.
     $P.NE.TMTLIB_BADFLAG)THEN
         R=SPGASC(TD,P)
         DEN=P/(R*T)
      ENDIF
      RETURN
      END
