      Function DETRM(ARRAY,NORDER)

C CALCULATE THE DETERMINATE OF A SQUARE MATRIX Function. SAME SOURCE
C   AS 'POLFIT'.

      DOUBLE PRECISION ARRAY, SAVE
      Dimension ARRAY(20,20)
      DETRM = 1.0
   11 DO 50 K=1, NORDER
C INTERCHANGE COLUMNS IF DIAGONAL ELEMENT IS ZERO.
      IF (ARRAY(K,K)) 41,21,41
   21 DO 23 J=K,NORDER
      IF (ARRAY(K,J)) 31,23,31
   23 Continue
      DETRM = 0.0
      GOTO 60
   31 DO 34 I=K, NORDER
      SAVE = ARRAY(I,J)
      ARRAY(I,J) = ARRAY(I,K)
   34 ARRAY(I,K) = SAVE
      DETRM =-DETRM
C SUBTRACT ROW K FROM LOWER ROWS TO GET DIAGONAL MATRIX.
   41 DETRM = DETRM*ARRAY(K,K)
      IF (K-NORDER) 43,50,50
   43 K1 = K + 1
      DO 46 I=K1, NORDER
      DO 46 J =K1, NORDER
   46 ARRAY(I,J) = ARRAY(I,J) - ARRAY(I,K)*ARRAY(K,J)/ARRAY(K,K)
   50 Continue
   60 Return
      End
