      SUBROUTINE POISSON_2D_MGR(F,G,MAXX,MAXY,NX,NY,DELX,DELY,BADDATA,
     $DO_CLEAN,CLEAN_THRESHOLD,P,ER1,ER2,N_CLEANED)

C  Thomas Matejka NOAA/NSSL 17 May 1996

      IMPLICIT NONE
      LOGICAL::DO_CLEAN
      INTEGER::MAXX,MAXY,
     $NX,NY,
     $N_CLEANED,
     $IDUM
      REAL::DELX,DELY,
     $BADDATA,
     $CLEAN_THRESHOLD,
     $ER1,ER2
      REAL,DIMENSION(MAXX,MAXY)::F,G,P,
     $F_TEMP,G_TEMP

      IF(DO_CLEAN)THEN
         CALL COPY_3D(F,MAXX,MAXY,1,NX,NY,1,F_TEMP)
         CALL COPY_3D(G,MAXX,MAXY,1,NX,NY,1,G_TEMP)
         CALL POISSON_2D(F_TEMP,G_TEMP,MAXX,MAXY,NX,NY,DELX,DELY,
     $   BADDATA,P)
         CALL ER_2D(P,F_TEMP,G_TEMP,MAXX,MAXY,NX,NY,DELX,DELY,BADDATA,
     $   .TRUE.,CLEAN_THRESHOLD,ER1,N_CLEANED)
         CALL POISSON_2D(F_TEMP,G_TEMP,MAXX,MAXY,NX,NY,DELX,DELY,
     $   BADDATA,P)
         CALL ER_2D(P,F_TEMP,G_TEMP,MAXX,MAXY,NX,NY,DELX,DELY,BADDATA,
     $   .FALSE.,0.,ER2,IDUM)
      ELSE
         CALL POISSON_2D(F,G,MAXX,MAXY,NX,NY,DELX,DELY,BADDATA,P)
         CALL ER_2D(P,F,G,MAXX,MAXY,NX,NY,DELX,DELY,BADDATA,.FALSE.,0.,
     $   ER1,N_CLEANED)
      ENDIF

      END SUBROUTINE POISSON_2D_MGR
