      SUBROUTINE PROBABILITY_DENSITY_HISTOGRAM(A,N,BADDATA,BIN_MIN,
     $BIN_INC,N_BINS,PROBABILITY_DENSITY_HIST,N_TOT)

C  Thomas Matejka NOAA/NSSL 15 July 1996

      IMPLICIT NONE
      INTEGER::N,N_TOT,N_BINS,I_BIN
      REAL::BADDATA,BIN_MIN,BIN_INC
      REAL,DIMENSION(N)::A
      REAL,DIMENSION(N_BINS)::PROBABILITY_HIST,PROBABILITY_DENSITY_HIST

      CALL PROBABILITY_HISTOGRAM(A,N,BADDATA,BIN_MIN,BIN_INC,N_BINS,
     $PROBABILITY_HIST,N_TOT)
      DO I_BIN=1,N_BINS
         PROBABILITY_DENSITY_HIST(I_BIN)=PROBABILITY_HIST(I_BIN)/BIN_INC
      ENDDO
      END
