      SUBROUTINE SURROUNDED_2D(FIRST,PHI,SURROUNDED)

C  Thomas Matejka, NOAA/NSSL 18 September 1997

      LOGICAL::FIRST,SURROUNDED
      REAL::PHI,PHI_PRIME
      REAL,SAVE::PHI_1,PHI_PRIME_L,PHI_PRIME_R

      IF(FIRST)THEN
         PHI_1=PHI
         PHI_PRIME_L=90.
         PHI_PRIME_R=270.
         SURROUNDED=.FALSE.
      ELSE
         PHI_PRIME=PHI-PHI_1
         IF(PHI_PRIME.LT.0.)THEN
            PHI_PRIME=PHI_PRIME+360.
         ENDIF
         IF(PHI_PRIME.GT.PHI_PRIME_L-90..AND.
     $   PHI_PRIME.LT.PHI_PRIME_L+90.)THEN
            PHI_PRIME_L=PHI_PRIME+90.
         ELSEIF(PHI_PRIME.GE.PHI_PRIME_R-90..AND.
     $   PHI_PRIME.LT.PHI_PRIME_R+90.)THEN
            PHI_PRIME_R=PHI_PRIME-90.
         ENDIF
         IF(PHI_PRIME_L.GT.PHI_PRIME_R)THEN
            SURROUNDED=.TRUE.
         ELSE
            SURROUNDED=.FALSE.
         ENDIF
      ENDIF
      END
